"""
G1 Manipulation Constants — indices and mappings for the Unitree G1 EDU.
Extracted from g1_manipulation_full.xml (46 DOF, 45 actuators, 10 sensors).
Generated by Plan 01 / Plan 02.
"""
import numpy as np

# ============================================================
# LOCOMOTION (12 DOF legs)
# ============================================================
LEG_LEFT_ACT_IDS = list(range(0, 6))    # [0,1,2,3,4,5]
LEG_RIGHT_ACT_IDS = list(range(6, 12))   # [6,7,8,9,10,11]
LEG_ACT_IDS = LEG_LEFT_ACT_IDS + LEG_RIGHT_ACT_IDS  # 12 total
LEG_JOINT_IDS = LEG_ACT_IDS              # joint[i+1] for act[i]

# ============================================================
# WAIST (3 DOF)
# ============================================================
WAIST_ACT_IDS = list(range(12, 15))      # [12,13,14]

# ============================================================
# HEAD (2 DOF)
# ============================================================
HEAD_ACT_IDS = [43, 44]

# ============================================================
# LEFT ARM (7 DOF: 5 arm + 2 wrist)
# ============================================================
ARM_LEFT_ACT_IDS = list(range(15, 22))   # shoulder_pitch=15 .. wrist_yaw=21
ARM_LEFT_JOINT_IDS = list(range(18, 25))  # joints 18-24

# ============================================================
# LEFT FINGERS (7 DOF)
# ============================================================
FINGER_LEFT_ACT_IDS = list(range(22, 29))  # thumb_0=22 .. index_1=28
FINGER_LEFT_JOINT_IDS = list(range(25, 32))  # joints 25-31

# ============================================================
# RIGHT ARM (7 DOF: 5 arm + 2 wrist)
# ============================================================
ARM_RIGHT_ACT_IDS = list(range(29, 36))   # shoulder_pitch=29 .. wrist_yaw=35
ARM_RIGHT_JOINT_IDS = list(range(32, 39))  # joints 32-38

# ============================================================
# RIGHT FINGERS (7 DOF)
# ============================================================
FINGER_RIGHT_ACT_IDS = list(range(36, 43))  # thumb_0=36 .. middle_1=42
FINGER_RIGHT_JOINT_IDS = list(range(39, 46))  # joints 39-45

# ============================================================
# MANIPULATION (28 DOF total: arms 14 + fingers 14)
# ============================================================
MANIP_LEFT_ACT_IDS = ARM_LEFT_ACT_IDS + FINGER_LEFT_ACT_IDS    # 14 DOF
MANIP_RIGHT_ACT_IDS = ARM_RIGHT_ACT_IDS + FINGER_RIGHT_ACT_IDS  # 14 DOF
MANIP_ALL_ACT_IDS = MANIP_LEFT_ACT_IDS + MANIP_RIGHT_ACT_IDS    # 28 DOF

# ============================================================
# TOUCH SENSORS (6 total: 3 per hand)
# ============================================================
TOUCH_LEFT_IDS = [12, 13, 14]   # sensordata indices: left_thumb, left_index, left_middle
TOUCH_RIGHT_IDS = [15, 16, 17]  # sensordata indices: right_thumb, right_index, right_middle
TOUCH_ALL_IDS = TOUCH_LEFT_IDS + TOUCH_RIGHT_IDS

TOUCH_LEFT_ADR = [12, 13, 14]   # alias (same as IDs)
TOUCH_RIGHT_ADR = [15, 16, 17]
TOUCH_ALL_ADR = TOUCH_LEFT_ADR + TOUCH_RIGHT_ADR

LIDAR_SENSOR_START_IDX = 18    # sensordata offset: after 4×3 IMU + 6×1 touch

# ============================================================
# IMU SENSORS
# ============================================================
IMU_TORSO_GYRO_ADR = (0, 3)     # sensordata[0:3]
IMU_TORSO_ACCEL_ADR = (3, 6)    # sensordata[3:6]
IMU_PELVIS_GYRO_ADR = (6, 9)    # sensordata[6:9]
IMU_PELVIS_ACCEL_ADR = (9, 12)  # sensordata[9:12]

# ============================================================
# TOTAL DIMENSIONS
# ============================================================
NQ = 53      # qpos dim (7 freejoint + 46 joints)
NV = 51      # qvel dim
NU = 45      # actuators
NSENSOR = 10  # sensors in robot XML (4 IMU + 6 touch)
SENSORDATA_DIM = 18  # 4*3 IMU + 6*1 touch

# ============================================================
# GRASP POLICY DIMENSIONS (Plan 02)
# ============================================================
GRASP_ARM_LEFT_DOFS = 7   # 5 shoulder/elbow + 2 wrist
GRASP_ARM_RIGHT_DOFS = 7
GRASP_FINGER_LEFT_DOFS = 7   # thumb(3) + index(2) + middle(2)
GRASP_FINGER_RIGHT_DOFS = 7
GRASP_TOUCH_PER_HAND = 3
GRASP_ACT_DIM = 28   # 14 left + 14 right
GRASP_OBS_DIM = 103  # 3+4 + 14+14 + 14+14 + 6+6 + 28

# Finger config (70% of range for closed, 10% for open — power grip)
# Left: act[22..28], Right: act[36..42]
FINGER_LEFT_OPEN = np.array([
    -0.8378,  # thumb_0
    -0.5472,  # thumb_1
    +0.1745,  # thumb_2
    -1.4137,  # middle_0
    -1.5708,  # middle_1
    -1.4137,  # index_0
    -1.5708,  # index_1
])
FINGER_LEFT_CLOSED = np.array([
    +0.4189,  # thumb_0
    +0.5157,  # thumb_1
    +1.2217,  # thumb_2
    -0.4712,  # middle_0
    -0.5236,  # middle_1
    -0.4712,  # index_0
    -0.5236,  # index_1
])
FINGER_RIGHT_OPEN = np.array([
    -0.8378,  # thumb_0
    -0.8700,  # thumb_1
    -1.5708,  # thumb_2
    +0.1571,  # middle_0
    +0.1745,  # middle_1
    +0.1571,  # index_0
    +0.1745,  # index_1
])
FINGER_RIGHT_CLOSED = np.array([
    +0.4189,  # thumb_0
    +0.1929,  # thumb_1
    -0.5236,  # thumb_2
    +1.0996,  # middle_0
    +1.2217,  # middle_1
    +1.0996,  # index_0
    +1.2217,  # index_1
])

# Box in scene XML (g1_manipulation_scene.xml)
BOX_BODY_ID = 48
BOX_JOINT_QPOS_ADR = 52   # qpos[52:59] = [x,y,z, qw,qx,qy,qz]
BOX_MASS = 1.0            # kg
BOX_SIZE = [0.15, 0.10, 0.15]  # half-sizes

# ============================================================
# MOTION POLICIES (Plan 02b — 29 DOF, no dexterous hands)
# ============================================================
MOTION_POLICY_DIR = "politicas/motions"
MOTION_POLICIES = {
    "saludar":        "politicas/motions/model_saludar_jit.pt",
    "agacharse":      "politicas/motions/model_agacharse_jit.pt",
    "estirar_brazos": "politicas/motions/model_estirar_brazos_jit.pt",
    "munecas":        "politicas/motions/model_munecas_jit.pt",
}
MOTION_OBS_DIM = 62   # q_actual(29) + q_target(29) + phase(1) + gravity(3)
MOTION_ACT_DIM = 29   # all DOF of g1_29dof

# Upper body DOF indices (in the 29-DOF vector)
UPPER_DOF_START = 12  # waist_yaw is first upper body DOF
UPPER_DOF_END   = 29  # 17 DOF upper (3 waist + 7 left arm + 7 right arm)
LOWER_DOF_START = 0
LOWER_DOF_END   = 12

# Specific joint indices (in the 29-DOF vector)
IDX_R_SHOULDER_PITCH = 22
IDX_R_SHOULDER_ROLL  = 23
IDX_R_ELBOW          = 25
IDX_R_WRIST_ROLL     = 26
IDX_R_WRIST_PITCH    = 27
IDX_L_KNEE           = 3
IDX_R_KNEE           = 9
